CREATE TABLE IF NOT EXISTS morkborg_characters (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    class_name  TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    cold_blood  TEXT NOT NULL DEFAULT '',
    exhaustion  TEXT NOT NULL DEFAULT '',
    abilities   JSONB NOT NULL DEFAULT '[]',
    strength    INT NOT NULL DEFAULT 10,
    agility     INT NOT NULL DEFAULT 10,
    toughness   INT NOT NULL DEFAULT 10,
    presence    INT NOT NULL DEFAULT 10,
    hp          INT NOT NULL DEFAULT 8,
    max_hp      INT NOT NULL DEFAULT 8,
    weapons     JSONB NOT NULL DEFAULT '[]',
    armor_name  TEXT NOT NULL DEFAULT '',
    armor_tier  TEXT NOT NULL DEFAULT '',
    sufferings  JSONB NOT NULL DEFAULT '[false,false,false,false,false,false]',
    equipment   JSONB NOT NULL DEFAULT '[]',
    silver      INT NOT NULL DEFAULT 0,
    omens       INT NOT NULL DEFAULT 3,
    omens_used  INT NOT NULL DEFAULT 0,
    notes       TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now()
);
