# Положи этот файл рядом с Dockerfile во фронтенд-репозитории
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: все пути отдают index.html (для react-router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
