services:
  backend-prod:
    image: ghcr.io/ilyaburch/vtm5e-charsheet/backend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"   # prod на 3001, чтобы не конфликтовать со staging
    env_file: .env.backend
    networks:
      - app-network

networks:
  app-network:
    external: true
